### ISSUE TITLE
SUGGESTIONS

### ISSUE THREAD

**Issue by ririko5834** [D3VSJ/BetterDiscordPanel#12]
Please add this:
- option to write messages in embed from (Discord MessageEmbed)
- Managing server (server settings, channel creation deletion perms override)
- Option to react to messages
- Option to leave server
- Option to find invite links on server

**Comment by ririko5834** [comment]
Bug report: avatar is not showed:
![image](https://user-images.githubusercontent.com/64729293/102011508-e4c33180-3d44-11eb-8e03-e89307a68ed4.png)
My bot have avatar and its not there

**Comment by ririko5834** [comment]
And also server icon is not shown

**Comment by ririko5834** [comment]
Another bug: messages are not deleted. It didnt work.
![image](https://user-images.githubusercontent.com/64729293/102011950-cf033b80-3d47-11eb-8fe6-49c39b02a195.png)

**Comment by ririko5834** [comment]
DM messages are not fetched

**Comment by D3VSJ** [comment]
Hey, most of the issues and suggestions have already been found and are added on the [BetterDiscordPanel Project] or have already been fixed. (https://github.com/D3VSJ/BetterDiscordPanel/projects/1).

In the next major release, the web panel will be replaced by a desktop application that should cover all of these issues.

**Comment by ririko5834** [comment]
Why? I think that web version is better. Please keep the web version

**Comment by D3VSJ** [comment]
As of my current plan, I will keep the web panel on the repository however the new desktop application will have much more support and updates.

**Comment by ririko5834** [comment]
Ok, but why are DM messages not fetched?

**Comment by D3VSJ** [comment]
That's another issue I will solve later, and probably will only be fixed in the new desktop application.

**Comment by ririko5834** [comment]
ok, when it wil be launched?

**Comment by D3VSJ** [comment]
Hopefully next year in January.

**Comment by ririko5834** [comment]
But thats sad that it will be not hostable on Glitch or vps :/ Why you are making desktop app?

**Comment by D3VSJ** [comment]
I’m planning a lot of features in the desktop application that isn’t really possible on web. If you have any more questions, could you please message me via discord or email me.
