### ISSUE TITLE
[BUG] - Emote and File attachment

### ISSUE THREAD

**Issue by spinfal** [D3VSJ/BetterDiscordPanel#13]
#### How major is the bug from 1 - 10
- Scale: **3**

#### What type of bug is it?
- Type: **A bug that has to do with the emote and file attachment feature**

#### Steps required to reproduce the bug
Steps: 
- **Login to your bot**
- **Go into a chat**
- **Click the emote/file button**

#### Screenshot (In most cases required)
- Screenshot: [**View Screenschot**](https://files.catbox.moe/guipie.png)

**Comment by D3VSJ** [comment]
Hey there, sorry to let you know but those buttons currently do not have any functions at the moment, I will remove those in the next update.

**Comment by D3VSJ** [comment]
Thank you for reminding me though 😁.

**Comment by spinfal** [comment]
Ah I see, no problem

**Comment by ririko5834** [comment]
Good idea

**Comment by D3VSJ** [comment]
Already fixed in the latest update.
