### ISSUE TITLE
[SUGGESTION] Add option to set custom bot status and activity

### ISSUE THREAD

**Issue by ririko5834** [D3VSJ/BetterDiscordPanel#14]
#### Suggestion Type
- Type:  Add option to set custom bot status and activity

- Description:  Can you please add that you can setup custom bot status (online, idle ,dnd ,invisible), presence type (watching, playing, competing, streaming) and custom presence

#### How would it help? 
It would help to manage the bot
#### Preview of the change
- Screenshots:

- Script:

**Comment by D3VSJ** [comment]
Sure! Thanks for the suggestion!

**Comment by ririko5834** [comment]
Also add option to change bot name and avatar

**Comment by D3VSJ** [comment]
Added to suggestions, thanks!

https://github.com/D3VSJ/BetterDiscordPanel/projects/1#card-51848317

**Comment by ririko5834** [comment]
And also the message deletion is not working, when it will be fixed? 
![image](https://user-images.githubusercontent.com/64729293/103167595-ac375380-482c-11eb-92da-0b5b2825eefb.png) when i click it is not working

**Comment by ririko5834** [comment]
Also I dont see member, role, emoji list 
![image](https://user-images.githubusercontent.com/64729293/103167607-cc671280-482c-11eb-892c-1821845e3b34.png)

**Comment by ririko5834** [comment]
And also add option to kick, ban, unban users, remove/add roles, override channel perms, manage channels

**Comment by D3VSJ** [comment]
> And also add option to kick, ban, unban users, remove/add roles, override channel perms, manage channels, manage roles

These suggestions have already been added to the project board.

> And also the message deletion is not working, when it will be fixed?

> ![image](https://user-images.githubusercontent.com/64729293/103167595-ac375380-482c-11eb-92da-0b5b2825eefb.png) when i click it is not working

I'm working on a solution to fix this.

> Also I dont see member, role, emoji list
> ![image](https://user-images.githubusercontent.com/64729293/103167607-cc671280-482c-11eb-892c-1821845e3b34.png)

Have you selected a server in the menu before opening this?

**Comment by ririko5834** [comment]
> Have you selected a server in the menu before opening this?
Yes

Also can you add that bot presence, guild count, user count, channel count will be showed in bot info card?

**Comment by D3VSJ** [comment]
> Also can you add that bot presence, guild count, user count, channel count will be showed in bot info card?

Sure, I will add this to the suggestions.

**Comment by D3VSJ** [comment]
> > Have you selected a server in the menu before opening this?
> 
> Yes

I can't seem to reproduce this issue, if you could send me a small video or screen share via discord, that would be great.

My Discord: D3VSJ#3158

**Comment by D3VSJ** [comment]
Also, which version of BetterDiscordPanel are you using? Does anything show up on the console? If so, could you screenshot that?

**Comment by ririko5834** [comment]
@D3VSJ here is screenshot, nothing in console
![image](https://user-images.githubusercontent.com/64729293/103211981-f2161980-4909-11eb-8e41-931ae29c5f5b.png)
I am using the newest version

**Comment by ririko5834** [comment]
Also when you will work on suggestions?

**Comment by D3VSJ** [comment]
> Also when you will work on suggestions?

I need some time to work on these suggestions since I have other projects and work to do. Please be patient.

**Comment by D3VSJ** [comment]
> @D3VSJ here is screenshot, nothing in console
> ![image](https://user-images.githubusercontent.com/64729293/103211981-f2161980-4909-11eb-8e41-931ae29c5f5b.png)

I will look into this later, thanks for pointing this out.
