### ISSUE TITLE
[SUGGESTION] - User banning

### ISSUE THREAD

**Issue by devilAPI** [D3VSJ/BetterDiscordPanel#3]
#### Suggestion Type
- Type: Administration

- Description: Makes possible banning a user from a selected Server

#### Preview of the change
- Screenshots: 

- Script:

**Comment by ririko5834** [comment]
Good idea 👍

**Comment by D3VSJ** [comment]
Added to suggestions. Thank you! 👍

https://github.com/D3VSJ/BetterDiscordPanel/projects/1#card-51515267
