### ISSUE TITLE
[SUGGESTION] - Creating and deleting channels

### ISSUE THREAD

**Issue by devilAPI** [D3VSJ/BetterDiscordPanel#4]
#### Suggestion Type
- Type: Administration

- Description: Makes creating and removing channels possible

#### Preview of the change
- Screenshots:

- Script:

**Comment by ririko5834** [comment]
Good idea 👍

**Comment by D3VSJ** [comment]
Added to suggestions. Thank you! 👍

https://github.com/D3VSJ/BetterDiscordPanel/projects/1#card-51515232
