### ISSUE TITLE
[SUGGESTION] - User role assignment

### ISSUE THREAD

**Issue by devilAPI** [D3VSJ/BetterDiscordPanel#5]
#### Suggestion Type
- Type: Administration

- Description: Bot can add and remove Roles from a user via dashboard

#### Preview of the change
- Screenshots:

- Script:

**Comment by ririko5834** [comment]
Good idea 👍

**Comment by D3VSJ** [comment]
Added to suggestions. Thank you! 👍

https://github.com/D3VSJ/BetterDiscordPanel/projects/1#card-51515167
