### ISSUE TITLE
[BUG] - Wrong token Login Loop

### ISSUE THREAD

**Issue by devilAPI** [D3VSJ/BetterDiscordPanel#6]
#### How major is the bug from 1 - 10
- Scale: 8

#### What type of bug is it?
- Type: Loop, Discord API Spam

#### Steps required to reproduce the bug
- Steps: 1. Get BDP on a WebServer 2. On the login page, type an invalid token

#### Screenshot (In most cases required)
- Screenshot: not needed, i think

**Comment by devilAPI** [comment]
It's impossible to get out of this loop, you HAVE TO switch browsers

**Comment by D3VSJ** [comment]
Issue has already been fixed.
