### ISSUE TITLE
[BUG] Geman Translation character bug

### ISSUE THREAD

**Issue by devilAPI** [D3VSJ/BetterDiscordPanel#7]
#### How major is the bug from 1 - 10
- Scale: 1

#### What type of bug is it?
- Type: language bug

#### Steps required to reproduce the bug
- Steps: run the cmd file with german translation on

#### Screenshot (In most cases required)
- Screenshot:

I am gonna create a pull reques, fixing this

**Comment by D3VSJ** [comment]
👍

**Comment by devilAPI** [comment]
#8
